// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaX9ohfrgFNkewq7mBFw5UUO0uttPtorA',
    appId: '1:137138853321:web:d64d6f2b26b2e061600418',
    messagingSenderId: '137138853321',
    projectId: 'appchat-cb7a0',
    authDomain: 'appchat-cb7a0.firebaseapp.com',
    storageBucket: 'appchat-cb7a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT-eJ3yqhLtnUfn7UURPzLCsicbk_4pm4',
    appId: '1:137138853321:android:e147eff6c363389f600418',
    messagingSenderId: '137138853321',
    projectId: 'appchat-cb7a0',
    storageBucket: 'appchat-cb7a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQLvlx6rU6XL7XsUkpPc8THZNBx4NOo1c',
    appId: '1:137138853321:ios:b0e0efc57eb6f5fd600418',
    messagingSenderId: '137138853321',
    projectId: 'appchat-cb7a0',
    storageBucket: 'appchat-cb7a0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQLvlx6rU6XL7XsUkpPc8THZNBx4NOo1c',
    appId: '1:137138853321:ios:b0e0efc57eb6f5fd600418',
    messagingSenderId: '137138853321',
    projectId: 'appchat-cb7a0',
    storageBucket: 'appchat-cb7a0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaX9ohfrgFNkewq7mBFw5UUO0uttPtorA',
    appId: '1:137138853321:web:be17f3b8861d220a600418',
    messagingSenderId: '137138853321',
    projectId: 'appchat-cb7a0',
    authDomain: 'appchat-cb7a0.firebaseapp.com',
    storageBucket: 'appchat-cb7a0.firebasestorage.app',
  );

}